### ISSUE TITLE
Why `cordova run` instead of `cordova build`?

### ISSUE THREAD

**Issue by janpio** [CookieCookson/cordova-plugin-lifecycle#4]
Is there a specific reason why the README mentions to use `cordova run` instead of `cordova build` to build the app? Normally `run`is used to just look at the current code iteration, and `build` to build the artifacts to be able to used manually, right?

**Comment by CookieCookson** [comment]
Correct, in the README I specify building and then using the run command. You can use the build command to just produce the APK/IPA or you can use run to produce the APK/IPA and also deploy it to the connected device/simulator.

**Comment by janpio** [comment]
Ok, so just your style of doing things but not a specific reason. Thanks.
