### ISSUE TITLE
Build config file does not exist : build.alpha.json

### ISSUE THREAD

**Issue by MaicolBen** [CookieCookson/cordova-plugin-lifecycle#7]
When I run:
`cordova run ios --alpha --buildConfig="build.alpha.json"` it throws me `Build config file does not exist : build.alpha.json`. Why could be that?

**Comment by CookieCookson** [comment]
Did you create a `build.alpha.json` in your project folder?

**Comment by MaicolBen** [comment]
I haven't read https://cordova.apache.org/docs/en/dev/guide/platforms/ios/index.html#using-buildjson.
Thanks!

**Comment by MaicolBen** [comment]
@CookieCookson Is there a way to set the app id for beta version? Like `com.test.staging`.

Thanks in advance

**Comment by CookieCookson** [comment]
Not without modifying the plugin directly no, sorry! There are a lot of references to the alpha/beta keyword throughout the source code so you would have to trawl through the source and find all instances of it to begin with. It would be a lot easier to use the keywords already provided 😇
